### ISSUE TITLE
'WITH_EDITORONLY_DATA' is not defined - Build failing on some build machines

### ISSUE THREAD

**Issue by pmsimardeidos** [nfrechette/acl-ue4-plugin#121]
Hello Nic,

Its been a while. I hope you are well :)

One of our build machine suddenly fail to compile the ACL plugin.

`...ACLPlugin\Source\ACLPlugin\Private\EditorDatabaseMonitor.cpp(3): error C4668: 'WITH_EDITORONLY_DATA' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'`

We're trying to figure out why this is happening exactly (could be how files are grouped together to build). Meanwhile, I'm posting a patch here to see if you think this could help avoid the issue.

[acl-ue4-plugin-bae22f8-Build fix for some compile target.patch](https://github.com/nfrechette/acl-ue4-plugin/files/10439536/acl-ue4-plugin-bae22f8-Build.fix.for.some.compile.target.patch)

**Comment by nfrechette** [comment]
Hey PM!
That is indeed a valid issue. I'm not sure why it hasn't popped up sooner since that code hasn't changed much in a while.
Your fix looks good. I'll see if I can integrate something similar in the next few days.

Thanks for the heads up and contribution!

**Comment by nfrechette** [comment]
Fixed by #122 
I'll make sure the fix is included with the next patch release that will include UE 5.2 support.
Thanks!

**Comment by nfrechette** [comment]
@all-contributors add @pmsimardeidos as code, bug
