### ISSUE TITLE
Slower Compress times with unreal 5.2

### ISSUE THREAD

**Issue by pmsimardeidos** [nfrechette/acl-ue4-plugin#132]
Hi Nic, 

I hope you're doing well :)

I just started using unreal 5.2 and I have a feeling (I did not do an actual diff to confirm) that the compression after a reimport in slower in 5.2 vs 5.1.

Is it just me? If you dont see that, we'll make sure to compare our import times to verify what could be the reason.

Thanks

PM

**Comment by nfrechette** [comment]
Hello PM,
I've been well, thanks!

The latest stable release 2.0.8 only contained minor fixes on the ACL end of things. There are minor additions that will slow things down but it shouldn't be a measurable difference. This [here](https://github.com/nfrechette/acl-ue4-plugin/blob/b5bb7f7df368de243ba2ed5c89757a0f319cd602/ACLPlugin/Source/ACLPlugin/Private/ACLImpl.cpp#L243) in particular is probably the biggest change but unless you have thousands of bones per skeleton, I doubt it would slow things down all that much that you'd notice. It should be on the order of 1ms or less.

I suspect that the slow down might come from UE 5.2 itself and not ACL. There were a number of changes in particular related to curves and the data model that holds the raw data. The slow down could be from there.

I haven't measured against UE in some time. I've been using UE 4.25 as the baseline performance measurement but for the next plugin release (2.1), I'll switch to UE 5.2 or 5.3 but that won't be for another few months.

I have some time off coming up next week, I'll see if I can run a quick regression test with ACL and the UE codecs to see if there has been any changes. I'll also bring up the issue internally but I think most people are off now, all of Epic has the first two weeks of July off.

I'll keep you posted.

Cheers,
Nicholas

**Comment by pmsimardeidos** [comment]
Hi Nicholas, I'll try to repro the issue to mesure the differences on a range of skeletons & animations.

**Comment by pmsimardeidos** [comment]
I'm still just looking at 5.2 but when reimporting an animation, we call FAnimationSequenceAsyncCacheTask numerous times in a row.

OnModelModified: After the fbximport

OnPropertyChanged: A null property is changed and it goes in this todo // @Todo fix me: This is temporary fix to make sure they always have compressed data

_Other OnModelModified when changing the animation in our own post processes... Those are on us :)_

I'll post it on UDN

**Comment by nfrechette** [comment]
Perfect, thanks!

**Comment by pmsimardeidos** [comment]
https://udn.unrealengine.com/s/question/0D54z00009P4KcvCAF/fanimationsequenceasynccachetask-triggerred-more-than-once-on-animsequence-reimport

**Comment by nfrechette** [comment]
Closing this ticket as the ACL Plugin is now distributed with the engine as part of UE 5.3. Support requests should be directed at UDN like you've done :)
Thanks!
