### ISSUE TITLE
Minor version checks look like they will fail on larger major versions

### ISSUE THREAD

**Issue by jamespark-unreal** [nfrechette/acl-ue4-plugin#133]
For example:
`#if ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 1`
will be false on 6.0, 7.0, etc.

**Comment by nfrechette** [comment]
That's correct, a lot of these checks aren't intended to work with future UE releases beyond 5.x and will require touch ups when 6.0 comes out.

Thankfully, that won't be necessary as with UE 5.3, the ACL plugin will come out of the box and Epic will maintain the plugin going forward with their internal fork. Epic is unlikely to be maintaining backwards compatibility for the plugin. These checks will get stripped in their fork.

I'll be announcing all of this very soon when UE 5.3 comes out and the readme here on github will be updated. There will only be one more official release for this plugin here on github and that will be for v2.1 (coming soon, ACL core development is done, I just have to polish up the plugin a bit, perform extensive testing, and extract stats to update charts, readmes, etc). Epic will take that update (UE 5.4 maybe 5.5, TBD) and continue the plugin development in their fork.

For these reasons, I won't be fixing these defines but thank you for catching it :)
