### ISSUE TITLE
Encountered an error while build Dedicated Server using clang 10.0.1 and AMD EPYC 7K83 CPU.

### ISSUE THREAD

**Issue by MORIZHIJIANDX** [nfrechette/acl-ue4-plugin#137]
Processor        AMD EPYC 7K83 64-Core Processor   2.54 GHz
Installed RAM        192 GB (189 GB usable)
Device ID        506B4908-0654-41AF-BC30-357C92B31A8E
Product ID        00454-60000-00001-AA819
System type        64-bit operating system, x64-based processor
Pen and touch        No pen or touch input is available for this display
Platform          Windows

Error:
`In file included from D:/machine/appbuildgroup/Intermediate/Build/Linux/B4D820EA/Server/Development/ACLPlugin/Module.ACLPlugin.gen.cpp:2:
In file included from D:/machine/appbuildgroup/Intermediate/Build/Linux/B4D820EA/Server/Inc/ACLPlugin/ACLImpl.gen.cpp:8:
In file included from ../Plugins/ACLPlugin/Source\ACLPlugin/Public/ACLImpl.h:85:
In file included from ../Plugins/ACLPlugin/Source/ThirdParty/acl/includes\acl/decompression/decompress.h:41:
In file included from ../Plugins/ACLPlugin/Source/ThirdParty/acl/includes\acl/decompression/impl/decompression_context_selector.h:30:
In file included from ../Plugins/ACLPlugin/Source/ThirdParty/acl/includes\acl/decompression/impl/decompression.transform.h:40:
D:\machine\appbuildgroup\EngineSource\Engine\Plugins\ACLPlugin\Source\ThirdParty\acl\includes\acl\decompression\impl\animated_track_cache.transform.h(1153,53): error: use of undeclared identifier '_mm_hadd_epi32'; did you mean '_mm_add_epi32'?
group_bit_size_per_component0_v = _mm_hadd_epi32(_mm_hadd_epi32(group_bit_size_per_component0_v, group_bit_size_per_component0_v), group_bit_size_per_component0_v);
                                                                              ^~~~~~~~~~~~~~
                                                                              _mm_add_epi32
C:\dev\UnrealToolchains\v17_clang-10.0.1-centos7\x86_64-unknown-linux-gnu\lib\clang\10.0.1\include\emmintrin.h(2161,1): note: '_mm_add_epi32' declared here
     _mm_add_epi32(__m128i __a, __m128i __b)
     ^`

**Comment by nfrechette** [comment]
Thank you for reporting this! I hadn't hit this edge case yet. It seems that some UE versions on linux enable SSE3 but not 4.1 which is uncommon these days. As a result, a header is missing in RTM.
To resolve your issue, you'll need to add an include in `rtm/math.h` under the `#if defined(RTM_SSE3_INTRINSICS)` section that includes the headers. Add this missing header: `#include <tmmintrin.h>`.

The next minor release of ACL is coming out in the next 4-6 weeks and will contain this fix and it should land in `develop` branch in the next few days as well.

Fix in RTM: https://github.com/nfrechette/rtm/pull/172

I'll close this issue once the `develop` branch contains the fix.

Cheers!

**Comment by MORIZHIJIANDX** [comment]
> Thank you for reporting this! I hadn't hit this edge case yet. It seems that some UE versions on linux enable SSE3 but not 4.1 which is uncommon these days. As a result, a header is missing in RTM. To resolve your issue, you'll need to add an include in `rtm/math.h` under the `#if defined(RTM_SSE3_INTRINSICS)` section that includes the headers. Add this missing header: `#include <tmmintrin.h>`.
> 
> The next minor release of ACL is coming out in the next 4-6 weeks and will contain this fix and it should land in `develop` branch in the next few days as well.
> 
> Fix in RTM: [nfrechette/rtm#172](https://github.com/nfrechette/rtm/pull/172)
> 
> I'll close this issue once the `develop` branch contains the fix.
> 
> Cheers!

Thank you for your prompt response！
