### ISSUE TITLE
Crash on Android ARM64 while ARMv7 is fine

### ISSUE THREAD

**Issue by nucleiis** [nfrechette/acl-ue4-plugin#27]
Hello,

I merged acl v0.4 plugin (with acl library v1.2.1) into UE 4.22 and everything so far works fine except Android ARM64.

On ARM64 it crashes at below callstack. It seems like reading at wrong address if it encounters any acl-compressed animation.

Any idea would be greatly appreciated!

01-30 10:25:52.892  6578  6578 F DEBUG   : backtrace:
01-30 10:25:52.893  6578  6578 F DEBUG   :     #00 pc 000000000463d4ac  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (__Float32x4_t acl::decompress_and_interpolate_vector<acl::uniformly_sampled::impl::TranslationDecompressionSettingsAdapter<acl::uniformly_sampled::DefaultDecompressionSettings>, 
acl::uniformly_sampled::impl::DecompressionContext, acl::uniformly_sampled::impl::SamplingContext>(acl::uniformly_sampled::impl::TranslationDecompressionSettingsAdapter<acl::uniformly_sampled::DefaultDecompressionSettings> const&, acl::
01-30 10:25:52.893  6578  6578 F DEBUG   :     #01 pc 000000000463decc  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (void acl::uniformly_sampled::DecompressionContext<acl::uniformly_sampled::DefaultDecompressionSettings>::decompress_pose<UE4OutputWriter<true, false, true>>(UE4OutputWriter<true, false, true>&)+336)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #02 pc 0000000004639d70  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (_ZN30AEFACLCompressionCodec_Default19GetPoseTranslationsER6TArrayI10FTransform18TMemStackAllocatorILj0EEERKS0_I13BoneTrackPair17FDefaultAllocatorER33FAnimSequenceDecompressionContext+948)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #03 pc 00000000068ead10  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (_Z32AnimationFormat_GetAnimationPoseR6TArrayI10FTransform18TMemStackAllocatorILj0EEERKS_I13BoneTrackPair17FDefaultAllocatorES9_S9_R33FAnimSequenceDecompressionContext+68)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #04 pc 0000000006954f44  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UAnimSequence::GetBonePose(FCompactPose&, FBlendedCurve&, FAnimExtractContext const&, bool) const+5168)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #05 pc 0000000006953558  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UAnimSequence::GetAnimationPose(FCompactPose&, FBlendedCurve&, FAnimExtractContext const&) const+780)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #06 pc 00000000069380f8  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SequencePlayer::Evaluate_AnyThread(FPoseContext&)+1960)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #07 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #08 pc 00000000063501e0  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_BlendListBase::Evaluate_AnyThread(FPoseContext&)+1312)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #09 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #10 pc 00000000063501e0  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_BlendListBase::Evaluate_AnyThread(FPoseContext&)+1312)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #11 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #12 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #13 pc 000000000693cf70  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_StateMachine::Evaluate_AnyThread(FPoseContext&)+1652)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #14 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #15 pc 0000000006936eb0  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SaveCachedPose::Evaluate_AnyThread(FPoseContext&)+168)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #16 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #17 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #18 pc 00000000063549d0  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_LayeredBoneBlend::Evaluate_AnyThread(FPoseContext&)+812)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #19 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #20 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #21 pc 0000000006942534  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_ConvertLocalToComponentSpace::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+92)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #22 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #23 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #24 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #25 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #26 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #27 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #28 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #29 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #30 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #31 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #32 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #33 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #34 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #35 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #36 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #37 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #38 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #39 pc 000000000638fd18  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+36)
01-30 10:25:52.893  6578  6578 F DEBUG   :     #40 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #41 pc 0000000006942040  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_ConvertComponentToLocalSpace::Evaluate_AnyThread(FPoseContext&)+76)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #42 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #43 pc 0000000006942534  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_ConvertLocalToComponentSpace::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+92)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #44 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #45 pc 0000000004ae0404  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FCustomBodyNode::EvaluateComponentSpace_AnyThread(FComponentSpacePoseContext&)+60)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #46 pc 00000000069412c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FComponentSpacePoseLink::EvaluateComponentSpace(FComponentSpacePoseContext&)+104)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #47 pc 0000000006942040  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimNode_ConvertComponentToLocalSpace::Evaluate_AnyThread(FPoseContext&)+76)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #48 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #49 pc 0000000004ae1f10  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FCustomFace::Evaluate_AnyThread(FPoseContext&)+176)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #50 pc 0000000006935e80  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FPoseLink::Evaluate(FPoseContext&)+108)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #51 pc 000000000690e20c  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimInstanceProxy::EvaluateAnimationNode(FPoseContext&)+920)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #52 pc 00000000068f6b7c  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FAnimInstanceProxy::EvaluateAnimation(FPoseContext&)+764)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #53 pc 00000000068f6794  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UAnimInstance::ParallelEvaluateAnimation(bool, USkeletalMesh const*, FBlendedHeapCurve&, FCompactPose&)+640)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #54 pc 0000000006afc338  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (USkeletalMeshComponent::EvaluateAnimation(USkeletalMesh const*, UAnimInstance*, FVector&, FBlendedHeapCurve&, FCompactPose&) const+804)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #55 pc 0000000006afca1c  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (_ZN22USkeletalMeshComponent26PerformAnimationProcessingEPK13USkeletalMeshP13UAnimInstancebR6TArrayI10FTransform17FDefaultAllocatorES9_R7FVectorR17FBlendedHeapCurve+988)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #56 pc 0000000006b018e4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (USkeletalMeshComponent::ParallelAnimationEvaluation()+92)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #57 pc 0000000006b00114  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (USkeletalMeshComponent::DoParallelEvaluationTasks_OnGameThread()+388)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #58 pc 0000000006aff090  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (USkeletalMeshComponent::RefreshBoneTransforms(FActorComponentTickFunction*)+7296)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #59 pc 0000000006af626c  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (USkeletalMeshComponent::InitAnim(bool, bool)+648)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #60 pc 0000000006af5ab4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (USkeletalMeshComponent::OnRegister()+76)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #61 pc 0000000006a7c044  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UActorComponent::ExecuteRegisterEvents()+648)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #62 pc 0000000006a7b5c4  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UActorComponent::RegisterComponentWithWorld(UWorld*)+2240)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #63 pc 0000000006891c74  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (AActor::IncrementalRegisterComponents(int)+1016)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #64 pc 0000000006da1234  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (ULevel::IncrementalUpdateComponents(int, bool)+1668)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #65 pc 00000000074caa48  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UWorld::UpdateWorldComponents(bool, bool)+376)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #66 pc 00000000074d8714  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UWorld::InitializeActorsForPlay(FURL const&, bool)+532)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #67 pc 00000000073fa880  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UEngine::LoadMap(FWorldContext&, FURL, UPendingNetGame*, FString&)+9092)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #68 pc 00000000073f655c  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UEngine::Browse(FWorldContext&, FURL, FString&)+2748)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #69 pc 00000000073f7dac  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UEngine::TickWorldTravel(FWorldContext&, float)+768)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #70 pc 0000000006c5e254  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (UGameEngine::Tick(float, bool)+3368)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #71 pc 000000000446f080  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (FEngineLoop::Tick()+22236)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #72 pc 0000000004467e78  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (AndroidMain(android_app*)+3552)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #73 pc 00000000044740fc  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so (android_main+148)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #74 pc 000000000448eea8  /data/app/com.XXX-k3tO3kZiJvYBUgd1kTiuCw==/lib/arm64/libUE4.so
01-30 10:25:52.894  6578  6578 F DEBUG   :     #75 pc 0000000000084df8  /system/lib64/libc.so (__pthread_start(void*)+208)
01-30 10:25:52.894  6578  6578 F DEBUG   :     #76 pc 0000000000023ac4  /system/lib64/libc.so (__start_thread+68)

**Comment by nfrechette** [comment]
Hello,
I ran into a similar issue when I released ACL 1.3, it seems to trigger a codegen bug. Does the crash happen if you disable optimizations?

You can also try the fix I made for 1.3: https://github.com/nfrechette/acl/commit/532a33a55ce4e58fdd038b0a4bcf838270e4585f

Can you add a snapshot of the instructions that are before/after the crashing one?

Thanks

**Comment by nucleiis** [comment]
@nfrechette Thank you for such a prompt reply,

I will merge your patch into acl 1.2.1 and let you know what happens, and disable optimizations. Regarding instructions, I failed to make Android Studio break at the moment of crash which is weird (breaks well with other exceptions).

**Comment by nucleiis** [comment]
@nfrechette I did merge your patch to acl 1.2.1 + UE4.22 and it works like a charm!

I didn't try other things like turning off optimizations and will let you know if there's any issue related with optimizations.

Have a nice day!

**Comment by nfrechette** [comment]
Awesome, glad to hear it!

**Comment by nfrechette** [comment]
@all-contributors add @nucleiis as bug reports
