### ISSUE TITLE
where to find Animation/AnimEncodingRegistry.h

### ISSUE THREAD

**Issue by cavefox** [nfrechette/acl-ue4-plugin#61]
I downloaded the 0.62 version of this plugin and setup it in the UE4 4.24.3.
When I compiling, It tips me "Error C1083 Cannot open include file: 'Animation/AnimEncodingRegistry.h': No such file or directory"
I don't know why or I missed something to do. Please help me out, thank you.

**Comment by nfrechette** [comment]
The [integration documentation](https://github.com/nfrechette/acl-ue4-plugin/tree/develop/Docs#engine-integration) should answer your questions. Version 0.6.x are for UE 4.24 and requires custom engine changes. The documentation [here](https://github.com/nfrechette/acl-ue4-plugin/blob/develop/Docs/pre_4_25_integration.md) will point you in the right direction.

Version 1.x are for UE 4.25 and can be installed from the Unreal Marketplace for free.
