### ISSUE TITLE
Support for a decompress_bone funtion that simply apply a default transform value to a BoneAtom

### ISSUE THREAD

**Issue by NoahZuo** [nfrechette/acl-ue4-plugin#79]
Hi, I am currently working on our avatar mask feature for our engine. 

For those bones that need to be ignored, I want to apply a default transform to the `BoneAtom` instead of calling `decompress_bone` function, which more or less, cost some performance. 

I've tried like this, but it cannot work: 
![image](https://user-images.githubusercontent.com/10735147/116179519-182db800-a74a-11eb-8b1b-0dfa90a0e45a.png)

How can I handle this problem please?

**Comment by nfrechette** [comment]
Hello,

I'm not sure I understand your intent here.

ACL decompresses only the bones that are 'desired' by the current LOD level and bone mask. If a bone/sub-track isn't desired, nothing is written in the output pose buffer and whatever value was there remains untouched (typically the bind pose or additive identity).

Are you saying that you wish to write your default transform/identity instead for sub-tracks that are skipped? For regular animations, you are likely to overwrite the bind pose which means all of their children will end up with the wrong offset. For additive animations, it might work but I would expect those to already have been initialized with the identity transform (are they not)? Are you attempting to do this for regular animations or for additive animations (or something else/custom)?

You could fill out the output pose with your identity value. Then ACL will skip the sub-tracks that are to be left alone. You'll do a bit more work that way though. Another way would be to modify the UE4 pose writer that is handed to ACL. ACL will call `skip_bone_rotation(..)` & friends once for each sub-track type. If that sub-track is skipped, you could write to the output buffer (more of a hack IMO..). I don't see any other way without modifying the ACL code. ACL doesn't call any function on the 'writer' provided when decompressing if a sub-track is skipped. You'd have to introduce a branch and call a function on the writer object that UE4 would implement and handle to write your default value.

What are you trying to achieve? The desired pairs specify which sub-tracks we care about and that end up being blended and read & written to. All the other values may not have values you can rely on or are explicitly masked out to avoid modifying them.

**Comment by NoahZuo** [comment]
What I am trying to do is to optimize the evaluation performance by applying an avatar mask to animation nodes. 

For example, if we have a layered bone blend node which have a full weight of the upper body bones in its child pose link. For this child pose link, only bones that in the upper body hierarchy should be evaluated. I hope this could save some performance for us.

**Comment by nfrechette** [comment]
As long as the `DesiredPairs` reflect the bones you care about, ACL will skip everything else and not output anything (when there are enough bones and we call `decompress_pose`). Are you looking at writing values to the non-desired bones or to just skip them and output nothing?

If you have performance problems due to the single bone decompression path, I would suggest you upgrade to ACL 1.3.5 or ACL 2.0 due to come out in the next few days. That is an old artifact from an earlier ACL version and shouldn't be required anymore. It should be faster to call decompress_pose and to skip the bones with the provided 'writer' object. You can also take a look at the latest plugin release to see how it looks. That heuristic that checks the number of bones and branches is no longer present.

ACL 2.0 leverages heavily bulk unpacking and cache prefetching. This means it is faster to decompress values we do not need and skip than it is to try and skip the data.

If you have animations that always play on the lower/upper body, you could perhaps make sure none of the other bones that will get masked out are animated. If they are constant (or the identity), unpacking/skipping them is very fast.

**Comment by NoahZuo** [comment]
Actually the `DesiredPairs` does not reflect the bones we really care about since we want to manually determine what bones we care using a layered bone blend node. 

As a result, we add an `int256` avartar mask in the `FPoseContext` to manually determine what bones should be evaluated. So we simply want to write default values to the ignored bones(For a upper body branch, simply ignore all lower body bones even though they are animated in the animation asset). 

Would this save some performance in your opinion?

**Comment by nfrechette** [comment]
Decompression is currently very fast with ACL 1.3.5 (and even faster with upcoming 2.0). On PC, XB1, and mobile, it's on the order of 1-15us per clip for ordinary characters. In my experience, most clips decompress in about 6-8us or less. Cutting down on the number of bones to decompress might speed things up but maybe not as much as you'd like. I don't think that cutting the number of bones in half would save half the decompression cost. It might not save that much on blending either if you have to introduce more branching on top of the desired pairs.

Many years ago, I implemented blending/decompression LOD support in a custom game engine by sorting the joints by LOD and simply stopping when we processed all the joints we needed. This had minimal branching and was supported by the blending and decompression. From memory, on XB1 it saved about 10% at most even on characters at the lowest LOD. It was quite underwhelming :(

What you are trying to achieve should work. If you test your bit set and skip the sub-tracks you don't need, everything should work. You can either skip the atom and writing nothing leaving whatever was there before or you could write the identity or bind pose (whatever you like). You can handle it the way you tried to when the bone count is low and we decompress bone by bone but for the branch below where we decompress the whole pose, you'll need to modify the `UE4OutputWriter` to test your bit set and act accordingly.
