### ISSUE TITLE
Crash when counting memory using v2.00

### ISSUE THREAD

**Issue by NoahZuo** [nfrechette/acl-ue4-plugin#82]
I am trying v2.00 in a 4.26-based demo project. 

This project is simply a third-person project which all animation sequences are compressed with ACL Database. 

When I try to type `memreport -full` command in the packed project, an error showed up: 

 
![image](https://user-images.githubusercontent.com/10735147/119334626-eb73ae80-bcbd-11eb-865c-48e5fedbbb97.png)

It seems that something is wrong with serialization: 
![image](https://user-images.githubusercontent.com/10735147/119334695-fe867e80-bcbd-11eb-93f5-31a60ca2fd44.png)

How can I handle this problem please? 

----

And btw, I simply commented this line of code, and it seems that we the bulk data size is counted twice: 

![image](https://user-images.githubusercontent.com/10735147/119365227-4f0fd300-bce2-11eb-8dfa-838b930b3a44.png)

For a bitwise compression, the memory report is like: 

![image](https://user-images.githubusercontent.com/10735147/119365422-7cf51780-bce2-11eb-95c9-768f30be2e72.png)

How should I handle it please?

**Comment by nfrechette** [comment]
Thank you for reporting this issue!

Indeed, data reporting seems problematic. In its current form, the assert can be skipped but the memory report will not be accurate. I played with this a bit tonight and it seems that bulk data isn't included either and in a lot of places, it isn't included for other asset types as well.

For ACL, I'll include the size of the bulk data in the memory report only for what is currently streamed in. This will require a few changes. I'll also have to retest a few things. I want to validate that data isn't present twice in memory and that everything is handled properly. The animation codec system from UE4 wasn't exactly written for this use case in mind and as such, it required some creativity to work within the confines of what it allows.

Give me a few days this week and I'll get back to you with a proposed fix. I would expect that sometime next week I should be able to push and release an update (perhaps sooner).

**Comment by nfrechette** [comment]
I made a fix for this in the linked PR #86 . Could you try it out and see if it resolves the issue for you as well?

The fix for the assert is in this commit: https://github.com/nfrechette/acl-ue4-plugin/pull/86/commits/1ddd799bc8a96386dbf67317d9add35dd211b8ed

The fix to properly track streamed in data is in this commit: https://github.com/nfrechette/acl-ue4-plugin/pull/86/commits/65424206ae243380f39ce2f5b5b9f3aacdf70b7b

Note that running the memreport in the editor may not yield accurate numbers but it should now work fine in a cooked build.

**Comment by NoahZuo** [comment]
Wow, this seems to work! Good job!
